---
- hosts: dbserver
  tasks:
  - name: execute any basic linux command
    command: hostname -f
    register: cmd_content
  - name: print variable contents
    debug:
      msg: "{{ cmd_content }}"  
      
    
    
    
    
    
    
    