---
- hosts:  all
  become: yes
  tasks:
  - name : first templete task 
    template: 
      src: firsttemplete.j2
      dest: /home/ansible/firsttem
  - name : second templete task 
    templete:
      src:  firsttemplete.j2
      dest: /home/ansible/secondtem   
