---
- hosts:  ubuntu
  become: yes
  tasks:
  - name : first templete task username is 
    template: 
      src: firsttemplete.j2
      dest: /home/ansible/firsttem
  - name : second templete task 
    templete:
      src:  second.j2
      dest: /home/ansible/secondtem   
