---
- hosts: ubuntu
  become: yes
  tasks :
  - name : first templete task username is 
    template: 
      src: firsttemplete.j2
      dest: /home/ansible/firsttem
  - name : sample templete with no dynamic content 
    template:
      src: second.j2
      dest: /home/ansible/samplecopy